package com.example.z1229.base;

import com.example.z1229.summerclient.R;

import java.util.ArrayList;
import java.util.Arrays;

public class EatBase {
    public static final String[] TAB = {"主食类", "肉蛋奶类", "蔬菜类", "水果类", "脂类", "饮料零食类"};

    public ArrayList<ItemInfo> ZS = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_mifan, 116, "米饭", 0),
            new ItemInfo(R.drawable.ph_huajuan, 214, "花卷", 0),
            new ItemInfo(R.drawable.ph_mantou, 223, "馒头", 0),
            new ItemInfo(R.drawable.ph_baozi, 227, "包子（猪肉）", 0),
            new ItemInfo(R.drawable.ph_baozisu, 166, "包子（素）", 0),
            new ItemInfo(R.drawable.ph_jiucaihezi, 211, "韭菜盒子", 0),
            new ItemInfo(R.drawable.ph_miantiaozhu, 110, "面条（煮）", 0),
            new ItemInfo(R.drawable.ph_miantiaosheng, 301, "面条（生）", 0),
            new ItemInfo(R.drawable.ph_miantiaobiaozhun, 301, "面条(标准粉，切面)", 0),
            new ItemInfo(R.drawable.ph_reganmian, 153, "热干面", 0),
            new ItemInfo(R.drawable.ph_liangmian, 167, "凉面", 0),
            new ItemInfo(R.drawable.ph_paomian, 473, "泡面", 0),
            new ItemInfo(R.drawable.ph_guamian, 348, "挂面", 0),
            new ItemInfo(R.drawable.ph_jingmizhou, 47, "粳米粥", 0),
            new ItemInfo(R.drawable.ph_ludouzhou, 48, "绿豆粥", 0),
            new ItemInfo(R.drawable.ph_xiaomizhou, 46, "小米粥", 0),
            new ItemInfo(R.drawable.ph_nanguazhou, 53, "南瓜粥", 0),
            new ItemInfo(R.drawable.ph_babaozhou, 85, "八宝粥", 0),
            new ItemInfo(R.drawable.ph_nangua, 31, "南瓜", 0),
            new ItemInfo(R.drawable.ph_liangfen, 38, "凉粉", 0),
            new ItemInfo(R.drawable.ph_yutou, 56, "芋头", 0),
            new ItemInfo(R.drawable.ph_shanyao, 57, "山药", 0),
            new ItemInfo(R.drawable.ph_tudou, 77, "马铃薯", 0),
            new ItemInfo(R.drawable.ph_guoqiaomixian, 92, "过桥米线", 0),
            new ItemInfo(R.drawable.ph_hongshu, 102, "红薯", 0),
            new ItemInfo(R.drawable.ph_baishu, 106, "白薯", 0),
            new ItemInfo(R.drawable.ph_changfen, 110, "肠粉", 0),
            new ItemInfo(R.drawable.ph_yumi, 112, "玉米", 0),
            new ItemInfo(R.drawable.ph_hongdou, 324, "红豆", 0)
    ));

    public ArrayList<ItemInfo> RDN = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_zhuroufei, 807, "猪肉（肥）", 0),
            new ItemInfo(R.drawable.ph_zhuroushou, 143, "猪肉（瘦）", 0),
            new ItemInfo(R.drawable.ph_zhuroufeishou, 143, "猪肉（肥瘦）", 0),
            new ItemInfo(R.drawable.ph_paigu, 568, "猪肉（排骨）", 0),
            new ItemInfo(R.drawable.ph_jirou, 133, "鸡肉", 0),
            new ItemInfo(R.drawable.ph_kaoya, 436, "烤鸭", 0),
            new ItemInfo(R.drawable.ph_yangrou, 118, "羊肉", 0),
            new ItemInfo(R.drawable.ph_yangrouchuan, 206, "羊肉串", 0),
            new ItemInfo(R.drawable.ph_niurou, 229, "牛肉", 0),
            new ItemInfo(R.drawable.ph_niurougan, 550, "牛肉干", 0),
            new ItemInfo(R.drawable.ph_huotuipian, 115, "火腿片", 0),
            new ItemInfo(R.drawable.ph_huotuichang, 212, "火腿肠", 0),
            new ItemInfo(R.drawable.ph_yuwan, 208, "鱼丸", 0),
            new ItemInfo(R.drawable.ph_jiaoziban, 223, "饺子/馄饨", 0),
            new ItemInfo(R.drawable.ph_hexie, 103, "河蟹", 0),
            new ItemInfo(R.drawable.ph_xiaren, 48, "虾仁", 0),
            new ItemInfo(R.drawable.ph_xiapi, 153, "虾皮", 0),
            new ItemInfo(R.drawable.ph_xiami, 198, "虾米", 0),
            new ItemInfo(R.drawable.ph_longxia, 90, "龙虾", 0),
            new ItemInfo(R.drawable.ph_caoyu, 113, "草鱼", 0),
            new ItemInfo(R.drawable.ph_liyu, 109, "鲤鱼", 0),
            new ItemInfo(R.drawable.ph_jiyu, 108, "鲫鱼", 0),
            new ItemInfo(R.drawable.ph_youyu, 75, "鱿鱼", 0),
            new ItemInfo(R.drawable.ph_nianyu, 146, "鲶鱼", 0),
            new ItemInfo(R.drawable.ph_daiyu, 127, "带鱼", 0),
            new ItemInfo(R.drawable.ph_jidan, 156, "鸡蛋", 0),
            new ItemInfo(R.drawable.ph_jidanqing, 60, "鸡蛋清", 0),
            new ItemInfo(R.drawable.ph_yadan, 180, "鸭蛋", 0),
            new ItemInfo(R.drawable.ph_anchundan, 160, "鹌鹑蛋", 0),
            new ItemInfo(R.drawable.ph_songhuadan, 171, "松花蛋", 0),
            new ItemInfo(R.drawable.ph_niunai, 54, "牛奶", 0),
            new ItemInfo(R.drawable.ph_yangnai, 59, "羊奶", 0),
            new ItemInfo(R.drawable.ph_suannai, 72, "酸奶", 0),
            new ItemInfo(R.drawable.ph_nainao, 328, "奶酪", 0)
    ));

    public ArrayList<ItemInfo> SC = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_mianxihugua, 10, "面西胡瓜", 0),
            new ItemInfo(R.drawable.ph_donggua, 11, "冬瓜", 0),
            new ItemInfo(R.drawable.ph_huangua, 15, "黄瓜", 0),
            new ItemInfo(R.drawable.ph_baigua, 10, "白瓜", 0),
            new ItemInfo(R.drawable.ph_haidai, 12, "海带", 0),
            new ItemInfo(R.drawable.ph_wawacai, 8, "娃娃菜", 0),
            new ItemInfo(R.drawable.ph_shuiqincai, 11, "水芹菜", 0),
            new ItemInfo(R.drawable.ph_sungua, 12, "笋瓜", 0),
            new ItemInfo(R.drawable.ph_bailuobo, 21, "白萝卜", 0),
            new ItemInfo(R.drawable.ph_fanqie, 19, "番茄", 0),
            new ItemInfo(R.drawable.ph_shengcai, 13, "生菜", 0),
            new ItemInfo(R.drawable.ph_wosun, 14, "莴笋", 0),
            new ItemInfo(R.drawable.ph_youmaicai, 15, "油麦菜", 0),
            new ItemInfo(R.drawable.ph_lvdouya, 18, "绿豆芽", 0),
            new ItemInfo(R.drawable.ph_qincaijing, 20, "芹菜茎", 0),
            new ItemInfo(R.drawable.ph_dabaicai, 17, "大白菜", 0),
            new ItemInfo(R.drawable.ph_hulu, 15, "葫芦", 0),
            new ItemInfo(R.drawable.ph_xioabaicia, 15, "小白菜", 0),
            new ItemInfo(R.drawable.ph_lianou, 74, "莲藕", 0),
            new ItemInfo(R.drawable.ph_huluobo, 41, "胡萝卜", 0),
            new ItemInfo(R.drawable.ph_muer, 265, "木耳", 0),
            new ItemInfo(R.drawable.ph_huacai, 20, "花菜", 0),
            new ItemInfo(R.drawable.ph_xilanhua, 34, "西兰花", 0),
            new ItemInfo(R.drawable.ph_bocai, 23, "菠菜", 0),
            new ItemInfo(R.drawable.ph_juanxincai, 12, "卷心菜", 0),
            new ItemInfo(R.drawable.ph_qiezi, 21, "茄子", 0),
            new ItemInfo(R.drawable.ph_qingjiao, 23, "青椒", 0),
            new ItemInfo(R.drawable.ph_yangcong, 39, "洋葱", 0),
            new ItemInfo(R.drawable.ph_kugua, 19, "苦瓜", 0),
            new ItemInfo(R.drawable.ph_maodou, 123, "毛豆", 0),
            new ItemInfo(R.drawable.ph_jiucai, 26, "韭菜", 0),
            new ItemInfo(R.drawable.ph_hongluobo, 22, "红萝卜", 0),
            new ItemInfo(R.drawable.ph_suantai, 61, "蒜苔", 0)
    ));

    public ArrayList<ItemInfo> SG = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_xigua, 26, "西瓜", 0),
            new ItemInfo(R.drawable.ph_shuimitao, 43, "水蜜桃", 0),
            new ItemInfo(R.drawable.ph_huangtao, 57, "黄桃", 0),
            new ItemInfo(R.drawable.ph_tiangua, 27, "甜瓜", 0),
            new ItemInfo(R.drawable.ph_mugua, 29, "木瓜", 0),
            new ItemInfo(R.drawable.ph_yangmei, 30, "杨梅", 0),
            new ItemInfo(R.drawable.ph_yangtao, 31, "杨桃", 0),
            new ItemInfo(R.drawable.ph_caomei, 32, "草莓", 0),
            new ItemInfo(R.drawable.ph_xueli, 79, "雪梨", 0),
            new ItemInfo(R.drawable.ph_yali, 45, "鸭梨", 0),
            new ItemInfo(R.drawable.ph_putaoyou, 33, "葡萄柚", 0),
            new ItemInfo(R.drawable.ph_youzi, 42, "柚子", 0),
            new ItemInfo(R.drawable.ph_hamigua, 34, "哈密瓜", 0),
            new ItemInfo(R.drawable.ph_pingguo, 54, "苹果", 0),
            new ItemInfo(R.drawable.ph_mangguo, 35, "芒果", 0),
            new ItemInfo(R.drawable.ph_lizi, 38, "李子", 0),
            new ItemInfo(R.drawable.ph_xingzi, 38, "杏子", 0),
            new ItemInfo(R.drawable.ph_ningmeng, 37, "柠檬", 0),
            new ItemInfo(R.drawable.ph_ximei, 39, "西梅", 0),
            new ItemInfo(R.drawable.ph_qingrenguo, 37, "情人果", 0),
            new ItemInfo(R.drawable.ph_pipa, 41, "琵琶", 0),
            new ItemInfo(R.drawable.ph_jvzi, 44, "橘子", 0),
            new ItemInfo(R.drawable.ph_youzi, 42, "柚子", 0),
            new ItemInfo(R.drawable.ph_putao, 44, "葡萄", 0),
            new ItemInfo(R.drawable.ph_hongtizi, 52, "红提子", 0),
            new ItemInfo(R.drawable.ph_mihoutao, 61, "猕猴桃", 0),
            new ItemInfo(R.drawable.ph_yingtao, 46, "樱桃", 0),
            new ItemInfo(R.drawable.ph_boluo, 44, "菠萝", 0),
            new ItemInfo(R.drawable.ph_boluomi, 105, "波罗蜜", 0),
            new ItemInfo(R.drawable.ph_heijialun, 46, "黑加仑", 0),
            new ItemInfo(R.drawable.ph_chengzi, 48, "橙子", 0),
            new ItemInfo(R.drawable.ph_shiliu, 73, "石榴", 0),
            new ItemInfo(R.drawable.ph_sangshen, 55, "桑葚", 0),
            new ItemInfo(R.drawable.ph_ganlan, 57, "橄榄", 0),
            new ItemInfo(R.drawable.ph_huolonguo, 60, "火龙果", 0),
            new ItemInfo(R.drawable.ph_wuhuaguo, 65, "无花果", 0),
            new ItemInfo(R.drawable.ph_ganzhe, 65, "甘蔗", 0),
            new ItemInfo(R.drawable.ph_shanzhu, 69, "山竹", 0),
            new ItemInfo(R.drawable.ph_xiangjiao, 93, "香蕉", 0),
            new ItemInfo(R.drawable.ph_lizhi, 71, "荔枝", 0),
            new ItemInfo(R.drawable.ph_guiyuan, 71, "桂圆", 0),
            new ItemInfo(R.drawable.ph_shizi, 74, "柿子", 0),
            new ItemInfo(R.drawable.ph_lanmei, 57, "蓝莓", 0),
            new ItemInfo(R.drawable.ph_liulian, 147, "榴莲", 0),
            new ItemInfo(R.drawable.ph_yezi, 241, "椰子", 0)
    ));

    public ArrayList<ItemInfo> ZL = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_chuntianrannaiyou, 230, "纯天然奶油", 0),
            new ItemInfo(R.drawable.ph_yetainaiyou, 273, "液态奶油", 0),
            new ItemInfo(R.drawable.ph_qiaokelinaiyou, 320, "巧克力奶油", 0),
            new ItemInfo(R.drawable.ph_huangyouzha, 599, "黄油渣", 0),
            new ItemInfo(R.drawable.ph_huangyou, 680, "黄油", 0),
            new ItemInfo(R.drawable.ph_huajiaoyou, 770, "花椒油", 0),
            new ItemInfo(R.drawable.ph_kuihuazitiaoheyou, 814, "葵花籽调和油（食用油）", 0),
            new ItemInfo(R.drawable.ph_ganlanyou, 822, "橄榄油", 0),
            new ItemInfo(R.drawable.ph_zhiwuyou, 826, "植物油", 0),
            new ItemInfo(R.drawable.ph_zhuyou, 827, "猪油", 0),
            new ItemInfo(R.drawable.ph_niuyou, 835, "牛油", 0),
            new ItemInfo(R.drawable.ph_shiyongtiaoheyou, 884, "食用调和油", 0),
            new ItemInfo(R.drawable.ph_huashengyou, 899, "花生油", 0),
            new ItemInfo(R.drawable.ph_yumiyou, 895, "玉米油", 0),
            new ItemInfo(R.drawable.ph_chuncaiyou, 900, "纯菜油", 0),
            new ItemInfo(R.drawable.ph_lajiaoyou, 900, "辣椒油", 0)
    ));

    public ArrayList<ItemInfo> YLLS = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_guodong, 70, "果冻", 0),
            new ItemInfo(R.drawable.ph_hongzao, 276, "红枣", 0),
            new ItemInfo(R.drawable.ph_binggun, 47, "冰棍", 0),
            new ItemInfo(R.drawable.ph_naitang, 407, "奶糖", 0),
            new ItemInfo(R.drawable.ph_niunaibinggan, 408, "牛奶饼干", 0),
            new ItemInfo(R.drawable.ph_bingqilin, 127, "冰淇淋", 0),
            new ItemInfo(R.drawable.ph_quqibing, 546, "曲奇饼", 0),
            new ItemInfo(R.drawable.ph_dangao, 348, "蛋糕", 0),
            new ItemInfo(R.drawable.ph_wangwangxuebing, 400, "旺旺雪饼", 0),
            new ItemInfo(R.drawable.ph_duoweishanzha, 249, "多味山楂", 0),
            new ItemInfo(R.drawable.ph_shibing, 255, "柿饼", 0),
            new ItemInfo(R.drawable.ph_qiaqiaguazi, 616, "恰恰香瓜子", 0),
            new ItemInfo(R.drawable.ph_heicafei, 1, "黑咖啡", 0),
            new ItemInfo(R.drawable.ph_chegnzhiqishui, 20, "橙汁汽水", 0),
            new ItemInfo(R.drawable.ph_kangshifumoliqingcha, 16, "康师傅茉莉清茶", 0),
            new ItemInfo(R.drawable.ph_jianjiaoyundongyinliao, 26, "尖叫运动饮料", 0),
            new ItemInfo(R.drawable.ph_ningmengcha, 27, "柠檬汁", 0),
            new ItemInfo(R.drawable.ph_weitamingqiaokelidounai, 57, "维他命巧克力豆奶饮料", 0),
            new ItemInfo(R.drawable.ph_kekoukele, 43, "可口可乐", 0),
            new ItemInfo(R.drawable.ph_pijiu, 27, "啤酒", 0),
            new ItemInfo(R.drawable.ph_huluobozhi, 24, "胡萝卜汁饮料", 0),
            new ItemInfo(R.drawable.ph_weiweidounai, 42, "维维豆奶", 0),
            new ItemInfo(R.drawable.ph_lvcha, 328, "绿茶", 0),
            new ItemInfo(R.drawable.ph_qiaokelidounai, 39, "巧克力豆奶", 0)
    ));

    public ArrayList<ItemInfo> SPORT = new ArrayList<>(Arrays.asList(
            new ItemInfo(R.drawable.ph_sanbu, 87, "散步",0),
            new ItemInfo(R.drawable.ph_manpao, 402, "慢跑",0),
            new ItemInfo(R.drawable.ph_shanglou, 469, "上楼",0),
            new ItemInfo(R.drawable.ph_xialou, 134, "下楼",0),
            new ItemInfo(R.drawable.ph_pinpangqiu, 201, "乒乓球",0),
            new ItemInfo(R.drawable.ph_jiawu, 168, "家务劳动",0),
            new ItemInfo(R.drawable.ph_zuofan, 101, "做饭",0),
            new ItemInfo(R.drawable.ph_liugou, 134, "遛狗",0),
            new ItemInfo(R.drawable.ph_qizixingche, 469, "骑自行车",0),
            new ItemInfo(R.drawable.ph_zoulushangxue, 154, "走路上班或上学",0),
            new ItemInfo(R.drawable.ph_youyong, 335, "游泳",0),
            new ItemInfo(R.drawable.ph_tabanji, 369, "踏板机",0),
            new ItemInfo(R.drawable.ph_yujia, 101, "瑜伽",0),
            new ItemInfo(R.drawable.ph_yumaoqiu, 235, "羽毛球",0)
    ));
}
